export const enum Materials{

    SHELL = "SHELL",
    HOWLITE ="HOWLITE",
    TURQUISE ="TURQUISE" ,
    BONE = "BONE",
    UNAKITE = "UNAKITE",
    PEARL = "PEARL",
    MOTHER_OF_PEARL="MOTHER_OF_PEARL",
    BAMBOO_CORAL="BAMBOO_CORAL", 
    HEMATITE ="HEMATITE",
    TIGER_EYE ="TIGER_EYE",
    MAGNESITE="MAGNESITE", 
    STONE= "STONE", 

    AMETHYST ="AMETHYST",
    ADVENTURINE ="ADVENTURINE",
    BLUE_ADVENTURINE ="BLUE_ADVENTURINE", 
    SERPENTINE ="SERPENTINE", 
    JASPER="JASPER",
    QUARTZITE = "QUARTZITE",
    AGATE ="AGATE",

    COPPER="COPPER",
    BRASS ="BRASS", 
    GUN_METAL_GREY ="GUN_METAL_GREY",
    DULL_SILVER_PLATED ="DULL_SILVER_PLATED",
    BRIGHT_SILVER_PLATED ="BRIGHT_SILVER_PLATED",
    GOLD_TONED_PLATED ="GOLD_TONED_PLATED", 

    STERLING_SILVER_PLATED ="STERLING_SILVER_PLATED", 
    FULL_STERLING_SILVER ="9FULL_STERLING_SILVER",
    GOLD ="GOLD",
    GOLD_PLATED = "GOLD_PLATED", 
    STAINLESS_STEEL ="STAINLESS_STEEL", 

    GLASS ="GLASS",
    CRYSTAL ="CRYSTAL",
    SWAROVSKI_CRYSTAL ="SWAROVSKI_CRYSTAL",
    GLASS_PEARL ="GLASS_PEARL",

    SEED ="SEED",

    PAPER ="PAPER",
    CERAMIC ="CERAMIC", 
    ACRYLIC="ACRYLIC", 
    WOOD ="WOOD", 
    PLASTIC = "PLASTIC",

    COTTON ="COTTON", 
    POLYESTER ="POLYESTER",
    WAXED_COTTON ="WAXED_COTTON", 
    LEATHER ="LEATHER", 
    FAUX_LEATHER ="FAUX_LEATHER",
    HEMP ="HEMP",
    OTHER ="OTHER",

}