export const enum StringWireCategory{
    BEADING_WIRE = "BEADING_WIRE",
    BEADING_THREAD = "BEADING_THREAD",
    ELASTIC = "ELASTIC",
    STRETCHY_FILAMENT = "STRETCHY_FILAMENT",
    NON_STRETCHY_FILAMENT = "NON_STRETCHY_FILAMENT",
    CORD = "CORD",
    CHAIN = "CHAIN",
    WRAPPING_WIRE = "WRAPPING_WIRE",
    MEMORY_WIRE = "MEMORY_WIRE"

}